create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  from_email text not null,
  to_email text not null,
  subject text not null,
  message text,
  sent_from text not null,
  submitted_at timestamptz not null default now(),
  submitted_at_local text,
  timezone text,
  locale text,
  user_agent text,
  page_url text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

drop policy if exists "Allow public inserts for contact messages" on public.contact_messages;
create policy "Allow public inserts for contact messages"
on public.contact_messages
for insert
to anon, authenticated
with check (true);
