/**
 * Command Registry
 * ─────────────────────────────────────────────────────────────────
 * Pure metadata — no handlers here. Add a new command by adding an
 * entry to COMMANDS.  The handler is keyed by `name` in useTerminal.
 */

export const COMMANDS = [
  // ── System ──────────────────────────────────────────────────────
  {
    name: 'help',
    aliases: ['?', 'h'],
    description: 'Show all available commands',
    usage: 'help [command]',
    category: 'System',
    keywords: ['help', 'commands', 'list', 'usage'],
  },
  {
    name: 'clear',
    aliases: ['cls', 'c'],
    description: 'Clear the terminal output',
    usage: 'clear',
    category: 'System',
    keywords: ['clear', 'reset', 'clean'],
  },
  {
    name: 'whoami',
    aliases: [],
    description: 'Display current user info',
    usage: 'whoami',
    category: 'System',
    keywords: ['whoami', 'user', 'who', 'identity'],
  },
  {
    name: 'pwd',
    aliases: [],
    description: 'Print working directory',
    usage: 'pwd',
    category: 'System',
    keywords: ['pwd', 'directory', 'path'],
  },
  {
    name: 'ls',
    aliases: ['dir', 'list'],
    description: 'List directory contents',
    usage: 'ls [path]',
    category: 'System',
    keywords: ['ls', 'list', 'dir', 'files'],
  },
  {
    name: 'echo',
    aliases: [],
    description: 'Print text to the terminal',
    usage: 'echo <text>',
    category: 'System',
    keywords: ['echo', 'print', 'say'],
  },
  {
    name: 'date',
    aliases: ['time'],
    description: 'Show current date and time',
    usage: 'date',
    category: 'System',
    keywords: ['date', 'time', 'clock', 'now'],
  },
  {
    name: 'theme',
    aliases: ['color'],
    description: 'Switch terminal colour theme',
    usage: 'theme [list | dark | dracula | nord | solarized]',
    category: 'System',
    keywords: ['theme', 'color', 'colours', 'appearance', 'skin'],
    subcommands: ['list', 'dark', 'dracula', 'nord', 'solarized'],
  },
  {
    name: 'neofetch',
    aliases: ['fetch', 'sysinfo'],
    description: 'Portfolio system information',
    usage: 'neofetch',
    category: 'System',
    keywords: ['neofetch', 'fetch', 'info', 'system', 'stats'],
  },

  // ── Portfolio ────────────────────────────────────────────────────
  {
    name: 'projects',
    aliases: ['proj', 'p', 'work'],
    description: 'Browse portfolio projects',
    usage: 'projects [list | open <name>]',
    category: 'Portfolio',
    keywords: ['projects', 'work', 'portfolio', 'code', 'apps'],
    subcommands: ['list', 'open'],
  },
  {
    name: 'articles',
    aliases: ['blog', 'posts'],
    description: 'Read blog articles',
    usage: 'articles [list | latest]',
    category: 'Portfolio',
    keywords: ['articles', 'blog', 'posts', 'writing', 'read'],
    subcommands: ['list', 'latest'],
  },
  {
    name: 'skills',
    aliases: ['stack', 'tech'],
    description: 'View tech stack and skills',
    usage: 'skills',
    category: 'Portfolio',
    keywords: ['skills', 'stack', 'tech', 'technologies', 'languages'],
  },
  {
    name: 'resume',
    aliases: ['cv', 'r'],
    description: 'Open the resume viewer',
    usage: 'resume',
    category: 'Portfolio',
    keywords: ['resume', 'cv', 'download', 'hire'],
  },
  {
    name: 'about',
    aliases: ['me', 'bio'],
    description: 'About me',
    usage: 'about',
    category: 'Portfolio',
    keywords: ['about', 'bio', 'me', 'who', 'developer'],
  },
  {
    name: 'contact',
    aliases: ['email', 'reach', 'hire'],
    description: 'Get contact information',
    usage: 'contact',
    category: 'Portfolio',
    keywords: ['contact', 'email', 'reach', 'hire', 'message'],
  },
  {
    name: 'socials',
    aliases: ['social', 'links'],
    description: 'Social media links',
    usage: 'socials',
    category: 'Portfolio',
    keywords: ['socials', 'social', 'twitter', 'github', 'links'],
  },
  {
    name: 'experience',
    aliases: ['exp', 'jobs', 'career'],
    description: 'Work experience',
    usage: 'experience',
    category: 'Portfolio',
    keywords: ['experience', 'jobs', 'work', 'career', 'history'],
  },
  {
    name: 'education',
    aliases: ['edu', 'school', 'degree'],
    description: 'Education background',
    usage: 'education',
    category: 'Portfolio',
    keywords: ['education', 'school', 'degree', 'university', 'study'],
  },
  {
    name: 'achievements',
    aliases: ['awards', 'wins', 'milestones'],
    description: 'Awards and hackathon milestones',
    usage: 'achievements',
    category: 'Portfolio',
    keywords: ['achievements', 'awards', 'wins', 'hackathon', 'milestones', 'prizes'],
  },

  // ── Navigation ───────────────────────────────────────────────────
  {
    name: 'open',
    aliases: ['launch', 'show'],
    description: 'Open a window or navigate to a project',
    usage: 'open <window | project>',
    category: 'Navigation',
    keywords: ['open', 'launch', 'show', 'goto', 'navigate', 'go', 'project', 'window'],
  },
  {
    name: 'goto',
    aliases: ['navigate', 'go', 'nav'],
    description: 'Alias for /open — navigate to a project or window',
    usage: 'goto <project-name | window>',
    category: 'Navigation',
    keywords: ['goto', 'navigate', 'go', 'project', 'jump'],
    hidden: true,
  },
  {
    name: 'search',
    aliases: ['find', 'grep', 'q'],
    description: 'Search across all portfolio content',
    usage: 'search <keyword>',
    category: 'Navigation',
    keywords: ['search', 'find', 'grep', 'query', 'lookup'],
  },

  // ── Fun / Easter eggs (hidden: true → not shown in /help) ────────
  {
    name: 'matrix',
    aliases: [],
    description: '🐇 Follow the white rabbit',
    usage: 'matrix',
    category: 'Fun',
    hidden: true,
    keywords: ['matrix'],
  },
  {
    name: 'sudo',
    aliases: [],
    description: '🔐 Nice try',
    usage: 'sudo <command>',
    category: 'Fun',
    hidden: true,
    keywords: ['sudo'],
  },
  {
    name: 'git',
    aliases: [],
    description: '🔧 Fake git commands',
    usage: 'git [log | status | blame]',
    category: 'Fun',
    hidden: true,
    keywords: ['git'],
    subcommands: ['log', 'status', 'blame'],
  },
  {
    name: 'npm',
    aliases: [],
    description: '📦 Running in the browser, silly',
    usage: 'npm install',
    category: 'Fun',
    hidden: true,
    keywords: ['npm'],
  },
];

/** Flat lookup map: includes name + all aliases → command entry */
export const COMMAND_MAP = Object.fromEntries([
  ...COMMANDS.map(cmd => [cmd.name, cmd]),
  ...COMMANDS.flatMap(cmd => (cmd.aliases ?? []).map(a => [a, cmd])),
]);
